# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my_proto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emy_proto.proto\x12\tmypackage\"`\n\tMyRequest\x12\x0f\n\x07id_card\x18\x01 \x01(\x05\x12\x13\n\x0bnumber_card\x18\x02 \x01(\x03\x12\x0b\n\x03\x63vc\x18\x03 \x01(\x05\x12\x0b\n\x03pin\x18\x04 \x01(\x05\x12\x13\n\x0b\x63ontract_id\x18\x05 \x01(\x05\"a\n\nMyResponse\x12\x0f\n\x07id_card\x18\x01 \x01(\x05\x12\x13\n\x0bnumber_card\x18\x02 \x01(\x03\x12\x0b\n\x03\x63vc\x18\x03 \x01(\x05\x12\x0b\n\x03pin\x18\x04 \x01(\x05\x12\x13\n\x0b\x63ontract_id\x18\x05 \x01(\x05\x32\x44\n\tMyService\x12\x37\n\x08MyMethod\x12\x14.mypackage.MyRequest\x1a\x15.mypackage.MyResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_proto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MYREQUEST._serialized_start=29
  _MYREQUEST._serialized_end=125
  _MYRESPONSE._serialized_start=127
  _MYRESPONSE._serialized_end=224
  _MYSERVICE._serialized_start=226
  _MYSERVICE._serialized_end=294
# @@protoc_insertion_point(module_scope)
